# Site settings
title: UCSB Web Standards Guide
email: webstandards@lists.ucsb.edu
description: >
  The UCSB Web Standards Guide is a guide to building semantic, accessible,
  and standards-compliant websites and web applications for the
  University of California, Santa Barbara
baseurl: "/"
url: "http://webguide.ucsb.edu/"
twitter_username: ucsantabarbara
github_username:  ucsb-wsg

# Add support for githubpages sitemap.xml.
gems:
  - jekyll-sitemap

# Build settings
exclude: [node_modules]

navigation:
  -
    categories:
      -
        name: 'Graphical Presentation'
        id: 'presentation'
        links:
          -
            text: Browsers
            url: browsers/
          -
            text: "Favicon and Touch Icons"
            url: favicon-and-touch-icons/
          -
            text: "UCSB Graphic Identity"
            url: ucsb-graphic-identity/
          -
            text: "Viewport Dimensions"
            url: viewport-dimensions/
      -
        name: 'Markup & Styling'
        id: 'markup'
        links:
          -
            text: CSS
            url: css/
          -
            text: Footer
            url: footer/
          -
            text: Header
            url: header/
          -
            text: HTML
            url: html/
          -
            text: Resources
            url: resources/
  -
    categories:
      -
        name: 'General Recommendations'
        id: 'recommendations'
        links:
          -
            text: "E-mail Addresses"
            url: email-addresses/
          -
            text: "Web Security"
            url: web-security/
          -
            text: URLs
            url: urls/
          -
            text: "Search Engine Optimization"
            url: seo/
          -
            text: "Frameworks"
            url: frameworks/
      -
        name: 'Policy Compliance'
        id: 'policy'
        links:
          -
            text: Policies
            url: policies/
          -
            text: "Web Accessibility"
            url: web-accessibility/
  -
    categories:
      -
        name: 'Resources'
        id: 'resources'
        links:
          -
            text: "Campus Resources"
            url: campus-resources/
          -
            text: "Examples"
            url: examples/
          -
            text: "Best Practices Templates"
            url: best-practice-templates/
          -
            text: "Web Standards Checklist"
            url: web-standards-checklist/
      -
        name: 'Behind the Standards'
        id: 'standards'
        links:
          -
            text: "About the WSG"
            url: about/
          -
            text: "Contact WSG"
            url: contact/
          -
            text: "Web Guide Site Map"
            url: site-map/
